<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('F '. $this->translate('Portalino'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>
        <!-- Scripts dodala za ZF2 data grid jqgrid -->
        <?php echo $this->headLink()->appendStylesheet('/jqGrid/css/ui.jqgrid.css')
                                    ->appendStylesheet('/css/jquery.ui.datepicker.css')
                                    ->appendStylesheet('/jqGrid/plugins/ui.multiselect.css') ;

              echo $this->headScript()->prependFile('http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js', 'text/javascript')
                                      ->prependFile('http://ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js', 'text/javascript')
                                      ->appendFile('/jqGrid/js/i18n/grid.locale-en.js', 'text/javascript')
                                      ->appendFile('/jqGrid/plugins/ui.multiselect.js', 'text/javascript')
                                      ->appendFile('/jqGrid/js/jquery.jqGrid.min.js', 'text/javascript') ; ?>                                     

    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Portalino') ?></a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                            <li class="active"><a href="<?php echo $this->url('zfcuser') ?>"><?php echo $this->translate('Sign Up') ?></a></li>
                            <li class="active"><a href="<?php echo $this->url('inspect') ?>"><?php echo $this->translate('Inspect') ?></a>
                              <ul>
                                <li><a href="<?php echo $this->url('inspect',array('action'=>'foo')); ?>"><?php echo $this->translate('Foo') ?></a></li>
                              </ul>
                            </li>  
                            <li><a href="">Table</a> 
                              <ul>
                                <li><a href="<?php echo $this->url('zftable',array('action'=>'base')); ?>"><?php echo $this->translate('Base') ?></a></li>
                                <li><a href="<?php echo $this->url('zftable',array('action'=>'data-table')); ?>"><?php echo $this->translate('Data Table') ?></a></li>
                                <li><a href="<?php echo $this->url('zftable',array('action'=>'mapper')); ?>"><?php echo $this->translate('Mapper') ?></a></li>
                                
                              </ul>  
                            </li> 
                            <li class="active"><a href="<?php echo $this->url('album') ?>"><?php echo $this->translate('Album') ?></a>
                              <ul>
                                <li><a href="<?php echo $this->url('album',array('action'=>'add')); ?>"><?php echo $this->translate('Add') ?></a></li>
                                <li><a href="<?php echo $this->url('album',array('action'=>'proba')); ?>"><?php echo $this->translate('Proba album') ?></a></li>
                              </ul>
                            </li>  
                            
                                                      
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - 2012 by Zend Technologies Ltd. OVO TREBA SKLONITI <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
