<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
   // zbog ovoga javlja fatal error treba zakomentarisati 
   /* 'Inspect\Module'                        => __DIR__ . '/Module.php',
    'Inspect\Controller\InspectController' => __DIR__ . '/src/Inspect/Controller/InspectController.php',
    'InspectTest\Framework\TestCase'        => __DIR__ . '/tests/Inspect/Framework/TestCase.php',
    'InspectTest\SampleTest'                => __DIR__ . '/tests/Inspect/SampleTest.php',*/
);
